#!/bin/bash
dpkg-deb -bZgzip projects/Pokemon_lockglyphs debs
dpkg-deb -bZgzip projects/Adinkra_Lockglyph debs
dpkg-deb -bZgzip projects/Ohio_Lockglyph debs
dpkg-deb -bZgzip projects/Sankofa_Lockglyph debs
dpkg-deb -bZgzip projects/Supreme_Lockglyph debs
dpkg-deb -bZgzip projects/Skull_Lockglyph debs
dpkg-deb -bZgzip projects/SHIELD_Lockglyphs debs
dpkg-deb -bZgzip projects/Circle_USA_Lockglyph debs
dpkg-deb -bZgzip projects/Noveske_Lockglyph debs
dpkg-deb -bZgzip projects/Magpul_Lockglyph debs
dpkg-deb -bZgzip projects/Ace_Lockglyph debs
dpkg-deb -bZgzip projects/Joker_Lockglyph debs
dpkg-deb -bZgzip projects/BreakingBad_Lockglyphs debs
dpkg-deb -bZgzip projects/Pangu_Lockglyph debs
dpkg-deb -bZgzip projects/Seahawks_Lockglyph debs
dpkg-deb -bZgzip projects/LTSJ6MODD debs
dpkg-deb -bZgzip projects/Spartan_Lockglyph debs
dpkg-deb -bZgzip projects/SouthB_Lockglyph debs
dpkg-deb -bZgzip projects/Hero_Lockglyphs debs
dpkg-deb -bZgzip projects/Transformers_Lockglyphs debs